### ISSUE TITLE
麻烦请问一下，视频的地址是怎么获取的？

### ISSUE THREAD

**Issue by Gavin888888** [clyhs/ABigFishTV#1]

**Comment by clyhs** [comment]
视频地址都是在论坛里收录的

**Comment by Gavin888888** [comment]
能发一下论坛的地址吗：）

**Comment by clyhs** [comment]
http://bbs.cnsat.net




| |
陈立宇
邮箱：clygd@126.com
|

签名由 网易邮箱大师 定制

在2018年03月30日 14:47，lilei 写道：

能发一下论坛的地址吗：）
