### ISSUE TITLE
iOS 11 崩溃

### ISSUE THREAD

**Issue by work4blue** [clyhs/ABigFishTV#3]
在语句中  
> self.window.rootViewController = [[ABFTabBarController alloc]init];

直接越界,但是找不到哪里有数组操作

>[DYMTLInitPlatform] platform initialization successful
2018-10-25 15:00:53.092223+0800 ABigFishTV[5232:667949] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 9223372036854775807 beyond bounds [0 .. 3]'
*** First throw call stack:
(0x1837aad8c 0x1829645ec 0x183743750 0x1837308cc 0x1049bcd3c 0x18d43dd78 0x18d43d7cc 0x18d43d468 0x104624550 0x18d3b9dbc 0x18d3b91c4 0x18d3865e0 0x18d9b6b1c 0x18d385dd0 0x18d385c6c 0x18d384afc 0x18e01a84c 0x18d3841ec 0x18ddffac8 0x18df4dbf8 0x18d383c0c 0x18d3835a8 0x18d3805e0 0x18d380330 0x185fac470 0x185fb4d6c 0x1067e119c 0x1067ed7cc 0x185fe0878 0x185fe051c 0x185fe0ab8 0x183753404 0x183752c2c 0x18375079c 0x183670da8 0x185656020 0x18d690758 0x1046766f8 0x183101fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by clyhs** [comment]
这个等我有空去调试下，你也可以查下首页的数组 ABFHomeViewController的 loadProvinceTVData
